default:
    resource: "@HelloDogBundle/Controller/DefaultController.php"
    type:     annotation

profile:
    resource: "@HelloDogBundle/Controller/ProfileController.php"
    type:     annotation

shop:
    resource: "@HelloDogBundle/Controller/ShopController.php"
    type:     annotation

admin:
    resource: "@HelloDogBundle/Controller/AdminController.php"
    type:     annotation